# Generated by Django 4.1.6 on 2023-09-21 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=3)),
                ('complaint', models.TextField(default='', max_length=500)),
                ('isHandled', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'ordering': ('priority', 'date_added'),
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exeat_type', models.CharField(max_length=255)),
                ('exeat_description', models.TextField(max_length=255)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('statusPorter', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('statusStudentAffairs', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('iscancelled', models.BooleanField(default=False)),
                ('isclearedbySecurity', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('tag', models.CharField(choices=[('primary', 'primary'), ('danger', 'danger'), ('success', 'success')], default='primary', max_length=255)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
