# Generated by Django 4.1.6 on 2023-09-24 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_exeat_type_forms_exeat_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'ordering': ('form_added',)},
        ),
        migrations.AddField(
            model_name='forms',
            name='form_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='forms',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
