# Generated by Django 4.1.6 on 2023-09-21 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usercat', models.CharField(choices=[('student', 'student'), ('porter', 'porter'), ('saffairs', 'saffairs'), ('security', 'security'), ('superuser', 'superuser')], max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('alternate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='users/cropped_img/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'lastname'),
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=255)),
                ('parent_phone_no', models.CharField(max_length=255)),
                ('alternate_parent_phone_no', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_email', models.EmailField(max_length=254)),
                ('student_level', models.CharField(blank=True, choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=5, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_general.departments')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_general.hostels')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'ordering': ('student',),
            },
        ),
        migrations.CreateModel(
            name='StudentAffairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentAffairsOfficer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'ordering': ('studentAffairsOfficer',),
            },
        ),
        migrations.CreateModel(
            name='Porters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_general.hostels')),
                ('porter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'ordering': ('porter',),
            },
        ),
    ]
