# Generated by Django 4.1.6 on 2023-09-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='room_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
