# Generated by Django 4.1.6 on 2023-09-22 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_students_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='forms_left_for_today',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='students',
            name='last_form_send_day',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
